# Generated by Django 5.0.3 on 2024-11-26 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Header',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header_image', models.ImageField(upload_to='statice/')),
                ('header_heading', models.CharField(max_length=100)),
                ('header_title', models.CharField(max_length=100)),
            ],
        ),
    ]
