# Generated by Django 5.0.3 on 2024-11-26 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_heading', models.CharField(max_length=100)),
                ('about_details', models.CharField(max_length=100)),
                ('about_image', models.ImageField(upload_to='static/')),
                ('about_sub_title', models.CharField(max_length=100)),
                ('about_sub_details', models.CharField(max_length=100)),
                ('about_birthday', models.CharField(max_length=100)),
                ('about_age', models.IntegerField()),
                ('about_website', models.CharField(max_length=100)),
                ('about_degree', models.CharField(max_length=100)),
                ('about_phone', models.IntegerField()),
                ('about_email', models.CharField(max_length=100)),
                ('about_city', models.CharField(max_length=100)),
                ('about_freelance', models.CharField(max_length=100)),
                ('about_bootm_details', models.CharField(max_length=100)),
            ],
        ),
    ]
