# Generated by Django 5.0.3 on 2024-11-26 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_about'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='about_bootm_details',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='about',
            name='about_details',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='about',
            name='about_sub_details',
            field=models.CharField(max_length=1000),
        ),
    ]
