# Generated by Django 5.0.3 on 2024-11-26 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_alter_about_about_bootm_details_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='about_phone',
            field=models.CharField(max_length=50),
        ),
    ]
