# Generated by Django 5.0.3 on 2024-11-26 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_alter_about_about_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_heading', models.CharField(max_length=100)),
                ('skill_progress', models.CharField(max_length=100)),
            ],
        ),
    ]
