# Generated by Django 5.0.3 on 2024-11-26 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_happyclient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='happyclient',
            name='happy_sub_title',
        ),
        migrations.AddField(
            model_name='happyclient',
            name='happy_image',
            field=models.ImageField(default=1, upload_to='static/'),
            preserve_default=False,
        ),
    ]
