# Generated by Django 5.0.3 on 2024-11-26 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_remove_happyclient_happy_sub_title_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('portfolio_text', models.CharField(max_length=1000)),
                ('portfolio_filed', models.CharField(max_length=100)),
                ('portfolio_image_1', models.ImageField(upload_to='static/')),
                ('portfolio_image_2', models.ImageField(upload_to='static/')),
                ('portfolio_image_3', models.ImageField(upload_to='static/')),
                ('portfolio_image_4', models.ImageField(upload_to='static/')),
                ('portfolio_image_5', models.ImageField(upload_to='static/')),
                ('portfolio_image_6', models.ImageField(upload_to='static/')),
            ],
        ),
    ]
