# Generated by Django 5.0.3 on 2024-11-26 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_remove_portfolio_portfolio_image_2_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Portfolio',
        ),
    ]
