# Generated by Django 5.0.3 on 2024-11-27 03:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_portfolio'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Portfolio',
        ),
    ]
