# Generated by Django 5.0.3 on 2024-11-27 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_delete_portfolio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('services_text', models.CharField(max_length=100)),
                ('services_title', models.CharField(max_length=100)),
                ('services_details', models.CharField(max_length=1000)),
            ],
        ),
    ]
