# Generated by Django 5.0.3 on 2024-11-27 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_services'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='services_image',
            field=models.ImageField(default=2, upload_to='static/'),
            preserve_default=False,
        ),
    ]
