# Generated by Django 5.0.3 on 2024-11-28 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0014_services_services_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testimonials_review', models.CharField(max_length=100)),
                ('testimonials_image', models.ImageField(upload_to='static/')),
                ('testimonials_name', models.CharField(max_length=100)),
                ('testimonails_post', models.CharField(max_length=100)),
            ],
        ),
    ]
