# Generated by Django 5.0.3 on 2024-11-28 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0015_testimonials'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_Address', models.CharField(max_length=100)),
                ('contact_Call', models.CharField(max_length=100)),
                ('contact_Email', models.CharField(max_length=100)),
                ('contact_map', models.CharField(max_length=100)),
            ],
        ),
    ]
