# Generated by Django 5.0.3 on 2024-11-28 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0016_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='sidebar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sidebar_image', models.ImageField(upload_to='static/')),
            ],
        ),
    ]
