# Generated by Django 5.0.3 on 2024-11-28 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0018_nav_delete_sidebar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='header',
            name='header_image',
            field=models.ImageField(upload_to='static/'),
        ),
    ]
